name: kapp
description: A new Flutter project.

version: 1.3.1+22

environment:
  sdk: ">=2.3.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  http: ^0.12.0+4
  provider: ^4.0.0
  grouped_buttons: ^1.0.4
  page_transition: ^1.1.5
  sqflite: ^1.2.0
  get_it: ^3.1.0
  path_provider: ^1.5.1
  connectivity: ^0.4.6+2
  image_picker: ^0.6.3+1
  intl: ^0.16.0
  dio: ^3.0.8
  device_info: ^0.4.1+4
  catcher: ^0.3.0
  cached_network_image: ^2.0.0
  font_awesome_flutter: ^8.7.0
  package_info: ^0.4.0+14
  background_fetch: ^0.5.4
  image_cropper: ^1.2.1
  jalali_calendar: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/applogo.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/splashscreen.jpg
   - assets/images/applogo.png
   - assets/locale/localization_pashto.json
   - assets/locale/localization_en.json
   - assets/locale/localization_dari.json
   - assets/images/addtask.png
   - assets/images/add.png
   - assets/images/reworkSurvey.png

  # example:arvo
  fonts:
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo-Bold.ttf
          style: normal
